import * as React from "react"
import { useQuery } from "@tanstack/react-query"
import { useNavigate } from "react-router-dom"
import { formatDistanceToNow } from "date-fns"
import { FileJson, FileText, Image, FileCode, Archive, File, Download, Search, Filter } from "lucide-react"
import { api } from "@/api/client"
import { queryKeys } from "@/api/query-keys"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

function getArtifactIcon(type: string) {
  switch (type) {
    case "json": return <FileJson className="h-5 w-5 text-primary" />
    case "report": return <FileText className="h-5 w-5 text-primary" />
    case "image": return <Image className="h-5 w-5 text-emerald-500" />
    case "code": return <FileCode className="h-5 w-5 text-yellow-500" />
    case "archive": return <Archive className="h-5 w-5 text-rose-500" />
    default: return <File className="h-5 w-5 text-muted-foreground" />
  }
}

function formatBytes(bytes: number, decimals = 2) {
  if (!+bytes) return '0 Bytes'
  const k = 1024
  const dm = decimals < 0 ? 0 : decimals
  const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`
}

export function ArtifactsList() {
  const navigate = useNavigate()
  const { data: artifacts = [], isLoading } = useQuery({
    queryKey: queryKeys.artifacts.all,
    queryFn: () => api.getArtifacts(),
  })
  
  const [search, setSearch] = React.useState("")

  const filtered = artifacts.filter(a => a.name.toLowerCase().includes(search.toLowerCase()))

  return (
    <div className="flex-1 space-y-8 p-8 max-w-7xl mx-auto w-full">
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Artifacts</h1>
          <p className="text-muted-foreground mt-1">Browse all files, reports, and data generated by your executions.</p>
        </div>
      </div>
      
      <div className="flex items-center gap-3">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input 
            placeholder="Search artifacts..." 
            className="pl-9 bg-surface-raised border-border"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <Button variant="outline">
          <Filter className="mr-2 h-4 w-4" />
          Filters
        </Button>
      </div>

      <div className="rounded-xl border border-border bg-surface-raised overflow-hidden">
        <table className="w-full text-sm text-left">
          <thead className="text-xs text-muted-foreground bg-surface-hover/50 uppercase border-b border-border">
            <tr>
              <th className="px-6 py-4 font-medium">Name</th>
              <th className="px-6 py-4 font-medium">Type</th>
              <th className="px-6 py-4 font-medium">Size</th>
              <th className="px-6 py-4 font-medium">Created</th>
              <th className="px-6 py-4 font-medium">Source Run</th>
              <th className="px-6 py-4 font-medium text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {isLoading ? (
              <tr>
                <td colSpan={6} className="px-6 py-8 text-center text-muted-foreground">Loading artifacts...</td>
              </tr>
            ) : filtered.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-6 py-8 text-center text-muted-foreground">No artifacts found.</td>
              </tr>
            ) : (
              filtered.map((artifact) => (
                <tr key={artifact.id} className="border-b border-border last:border-0 hover:bg-surface-hover/30 transition-colors">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      {getArtifactIcon(artifact.type)}
                      <span className="font-medium">{artifact.name}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4 capitalize">{artifact.type}</td>
                  <td className="px-6 py-4 text-muted-foreground">{formatBytes(artifact.sizeBytes || 0)}</td>
                  <td className="px-6 py-4 text-muted-foreground">{formatDistanceToNow(new Date(artifact.createdAt), { addSuffix: true })}</td>
                  <td className="px-6 py-4">
                    <button 
                      onClick={() => navigate(`/app/runs/${artifact.runId}`)}
                      className="text-primary hover:underline font-mono text-xs"
                    >
                      {artifact.runId}
                    </button>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <Button variant="ghost" size="sm">
                      <Download className="mr-2 h-4 w-4" />
                      Download
                    </Button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}
