# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alter/memory/v1/memory.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'alter/memory/v1/memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61lter/memory/v1/memory.proto\x12\x0f\x61lter.memory.v1\"\x91\x01\n\x17ProposeWritebackRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x14\n\x0cworkspace_id\x18\x02 \x01(\t\x12\x0e\n\x06run_id\x18\x03 \x01(\t\x12#\n\x1bverified_output_artifact_id\x18\x04 \x01(\t\x12\x11\n\tnamespace\x18\x05 \x01(\tJ\x05\x08\x64\x10\xc8\x01\"L\n\x18ProposeWritebackResponse\x12\x11\n\tmemory_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63\x61ndidate_json\x18\x02 \x01(\tJ\x05\x08\x64\x10\xc8\x01\"\x94\x01\n\x14PromoteMemoryRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x11\n\tmemory_id\x18\x02 \x01(\t\x12\x19\n\x11\x65valuation_run_id\x18\x03 \x01(\t\x12\x1e\n\x11\x61\x64s_core_scope_id\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x14\n\x12_ads_core_scope_idJ\x05\x08\x64\x10\xc8\x01\"E\n\x15PromoteMemoryResponse\x12\x10\n\x08promoted\x18\x01 \x01(\x08\x12\x13\n\x0bpromoted_at\x18\x02 \x01(\tJ\x05\x08\x64\x10\xc8\x01\"o\n\x13UpdatePolicyRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x11\n\tpolicy_id\x18\x02 \x01(\t\x12\x17\n\x0f\x63urrent_version\x18\x03 \x01(\t\x12\x12\n\npatch_json\x18\x04 \x01(\tJ\x05\x08\x64\x10\xc8\x01\"E\n\x14UpdatePolicyResponse\x12\x11\n\tpolicy_id\x18\x01 \x01(\t\x12\x13\n\x0bnew_version\x18\x02 \x01(\tJ\x05\x08\x64\x10\xc8\x01\x32\xb5\x02\n\rMemoryService\x12g\n\x10ProposeWriteback\x12(.alter.memory.v1.ProposeWritebackRequest\x1a).alter.memory.v1.ProposeWritebackResponse\x12^\n\rPromoteMemory\x12%.alter.memory.v1.PromoteMemoryRequest\x1a&.alter.memory.v1.PromoteMemoryResponse\x12[\n\x0cUpdatePolicy\x12$.alter.memory.v1.UpdatePolicyRequest\x1a%.alter.memory.v1.UpdatePolicyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alter.memory.v1.memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROPOSEWRITEBACKREQUEST']._serialized_start=50
  _globals['_PROPOSEWRITEBACKREQUEST']._serialized_end=195
  _globals['_PROPOSEWRITEBACKRESPONSE']._serialized_start=197
  _globals['_PROPOSEWRITEBACKRESPONSE']._serialized_end=273
  _globals['_PROMOTEMEMORYREQUEST']._serialized_start=276
  _globals['_PROMOTEMEMORYREQUEST']._serialized_end=424
  _globals['_PROMOTEMEMORYRESPONSE']._serialized_start=426
  _globals['_PROMOTEMEMORYRESPONSE']._serialized_end=495
  _globals['_UPDATEPOLICYREQUEST']._serialized_start=497
  _globals['_UPDATEPOLICYREQUEST']._serialized_end=608
  _globals['_UPDATEPOLICYRESPONSE']._serialized_start=610
  _globals['_UPDATEPOLICYRESPONSE']._serialized_end=679
  _globals['_MEMORYSERVICE']._serialized_start=682
  _globals['_MEMORYSERVICE']._serialized_end=991
# @@protoc_insertion_point(module_scope)
