import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("@alterx/contracts built package", () => {
  it("loads built runtime exports in a plain Node subprocess", () => {
    const output = execFileSync(
      process.execPath,
      [
        "-e",
        `
          const { resolve } = require("node:path");
          const packageRoot = resolve(process.cwd(), "packages/contracts");
          const expectedEntry = resolve(packageRoot, "dist/index.js");
          if (require.resolve(packageRoot) !== expectedEntry) process.exit(1);
          const builtPackage = require(packageRoot);
          for (const name of [
            "CanonicalEventSchema",
            "CompiledDagSchema",
            "FailureClassSchema",
            "RootCauseEstimateSchema",
            "WorkflowDagCompiledSchema",
            "SseEnvelopeSchema",
          ]) {
            if (!(name in builtPackage)) process.exit(2);
          }
          process.stdout.write("built package import ok");
        `,
      ],
      { cwd: process.cwd(), encoding: "utf8" },
    );

    expect(output).toBe("built package import ok");
  });

  it("exports generated audit proto request and response declarations", () => {
    const declarations = readFileSync(
      "packages/contracts/dist/index.d.ts",
      "utf8",
    );
    expect(declarations).toContain("RecordEventRequest");
    expect(declarations).toContain("RecordEventResponse");
    expect(
      readFileSync(
        "packages/contracts/src/generated/alter/audit/v1/audit.ts",
        "utf8",
      ),
    ).toContain("Code generated by protoc-gen-ts_proto");
  });

  it("exports generated modelgw proto request and response declarations", () => {
    const declarations = readFileSync(
      "packages/contracts/dist/index.d.ts",
      "utf8",
    );
    expect(declarations).toContain("ModelgwInvokeRequest");
    expect(declarations).toContain("ModelgwInvokeResponse");
    expect(
      readFileSync(
        "packages/contracts/src/generated/alter/modelgw/v1/modelgw.ts",
        "utf8",
      ),
    ).toContain("Code generated by protoc-gen-ts_proto");
  });

  it("exports generated recovery proto request and response declarations", () => {
    const declarations = readFileSync(
      "packages/contracts/dist/index.d.ts",
      "utf8",
    );
    expect(declarations).toContain("RecoveryClassifyFailureRequest");
    expect(declarations).toContain("RecoveryClassifyFailureResponse");
    expect(
      readFileSync(
        "packages/contracts/src/generated/alter/recovery/v1/recovery.ts",
        "utf8",
      ),
    ).toContain("Code generated by protoc-gen-ts_proto");
  });
});
