import { useParams, useNavigate } from "react-router-dom"
import { useQuery } from "@tanstack/react-query"
import { formatDistanceToNow } from "date-fns"
import { GitCommit, RotateCcw } from "lucide-react"
import { api } from "@/api/client"
import { queryKeys } from "@/api/query-keys"
import { Button } from "@/components/ui/button"
import { toast } from "sonner"

export function WorkflowVersions() {
  const { workflowId } = useParams()
  const navigate = useNavigate()

  const { data: workflow, isLoading } = useQuery({
    queryKey: queryKeys.workflows.detail(workflowId!),
    queryFn: () => api.getWorkflow(workflowId!),
    enabled: !!workflowId,
  })

  // Mock versions data
  const mockVersions = [
    { id: "v3", version: 3, summary: "Added Slack escalation routing", createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(), createdBy: "Ameen" },
    { id: "v2", version: 2, summary: "Changed urgency classifier prompt", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), createdBy: "Sarah Chen" },
    { id: "v1", version: 1, summary: "Initial workflow generated by AlterX", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), createdBy: "Ameen" },
  ]

  const handleRollback = (version: number) => {
    toast.success(`Workflow rolled back to version ${version}. A new version was created.`)
    navigate(`/app/workflows/${workflowId}/build`)
  }

  if (isLoading || !workflow) return null

  return (
    <div className="flex-1 space-y-8 p-8 max-w-4xl mx-auto">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Version History</h1>
        <p className="mt-2 text-muted-foreground">{workflow.name}</p>
      </div>

      <div className="space-y-4">
        {mockVersions.map((v, i) => (
          <div key={v.id} className="flex gap-4 rounded-xl border border-border bg-surface-raised p-6">
            <div className="flex flex-col items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-primary">
                <GitCommit className="h-4 w-4" />
              </div>
              {i !== mockVersions.length - 1 && <div className="h-full w-px bg-border" />}
            </div>
            <div className="flex-1 space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-semibold flex items-center gap-2">
                    Version {v.version}
                    {i === 0 && <span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-xs font-medium text-emerald-500">Current</span>}
                  </h3>
                  <p className="text-sm text-muted-foreground mt-1">{v.summary}</p>
                </div>
                <div className="text-right">
                  <p className="text-sm text-foreground/90">{formatDistanceToNow(new Date(v.createdAt), { addSuffix: true })}</p>
                  <p className="text-xs text-muted-foreground mt-1">by {v.createdBy}</p>
                </div>
              </div>
              {i !== 0 && (
                <div className="flex gap-2 pt-2">
                  <Button variant="outline" size="sm" onClick={() => handleRollback(v.version)}>
                    <RotateCcw className="mr-2 h-4 w-4" />
                    Rollback to this
                  </Button>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
