# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alter/capability/v1/capability.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'alter/capability/v1/capability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$alter/capability/v1/capability.proto\x12\x13\x61lter.capability.v1\"\x89\x01\n\x1eResolveNodeRequirementsRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x10\n\x08node_key\x18\x03 \x01(\t\x12\x11\n\tnode_type\x18\x04 \x01(\t\x12\x18\n\x10node_config_json\x18\x05 \x01(\tJ\x05\x08\x64\x10\xc8\x01\"`\n\x1fResolveNodeRequirementsResponse\x12\x1e\n\x16node_requirements_json\x18\x01 \x01(\t\x12\x16\n\x0eschema_version\x18\x02 \x01(\tJ\x05\x08\x64\x10\xc8\x01\x32\x9a\x01\n\x11\x43\x61pabilityService\x12\x84\x01\n\x17ResolveNodeRequirements\x12\x33.alter.capability.v1.ResolveNodeRequirementsRequest\x1a\x34.alter.capability.v1.ResolveNodeRequirementsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alter.capability.v1.capability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOLVENODEREQUIREMENTSREQUEST']._serialized_start=62
  _globals['_RESOLVENODEREQUIREMENTSREQUEST']._serialized_end=199
  _globals['_RESOLVENODEREQUIREMENTSRESPONSE']._serialized_start=201
  _globals['_RESOLVENODEREQUIREMENTSRESPONSE']._serialized_end=297
  _globals['_CAPABILITYSERVICE']._serialized_start=300
  _globals['_CAPABILITYSERVICE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
