import { z } from "zod";
import { RegistryHttpError } from "./problem";
import { ecosystems, trustLevels, type CreateManifestInput, type CreateVersionInput } from "./types";
const semver = /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/;
const id = /^(?:tlm|tlv)_[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function parse<T>(schema: z.ZodType<T>, input: unknown, instance: string): T { const result = schema.safeParse(input); if (result.success) return result.data; throw new RegistryHttpError(400, "INVALID_REGISTRY_REQUEST", "Registry request validation failed", instance, result.error.issues.map((issue) => ({ field: issue.path.join(".") || "body", message: issue.message }))); }
const manifest = z.object({ name: z.string().trim().min(1).max(255), ecosystem: z.enum(ecosystems), description: z.string().trim().min(1).max(10_000).optional(), trust_level: z.enum(trustLevels), publisher_id: z.string().min(1).optional() }).strict();
const version = z.object({ version: z.string().regex(semver, "Expected semantic version"), artifact_ref: z.string().min(1).max(2_048), capabilities: z.array(z.string().trim().min(1).max(255)).max(500), permissions: z.array(z.string().trim().min(1).max(255)).max(500), pinned: z.boolean().optional() }).strict();
export function parseCreateManifest(input: unknown, instance: string): CreateManifestInput { const value = parse(manifest, input, instance); return { name: value.name, ecosystem: value.ecosystem, trust_level: value.trust_level, ...(value.description === undefined ? {} : { description: value.description }), ...(value.publisher_id === undefined ? {} : { publisher_id: value.publisher_id }) }; }
export function parseCreateVersion(input: unknown, instance: string): CreateVersionInput { const value = parse(version, input, instance); return { version: value.version, artifact_ref: value.artifact_ref, capabilities: value.capabilities, permissions: value.permissions, ...(value.pinned === undefined ? {} : { pinned: value.pinned }) }; }
export function parseManifestId(value: string, instance: string): string { if (!/^tlm_[0-9a-f-]+$/i.test(value)) throw new RegistryHttpError(400, "INVALID_REGISTRY_REQUEST", "Registry request validation failed", instance, [{ field: "manifestId", message: "Expected manifest UUIDv7" }]); return value; }
export function parseVersionId(value: string, instance: string): string { if (!id.test(value) || !value.startsWith("tlv_")) throw new RegistryHttpError(400, "INVALID_REGISTRY_REQUEST", "Registry request validation failed", instance, [{ field: "versionId", message: "Expected version UUIDv7" }]); return value; }
export function parseRevocation(input: unknown, instance: string): { reason: string } { return parse(z.object({ reason: z.string().trim().min(1).max(1_000) }).strict(), input, instance); }
