import { useQuery } from "@tanstack/react-query"
import { PageHeader } from "@/components/common/page-header"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { api } from "@/api/client"
import { queryKeys } from "@/api/query-keys"
import { formatCurrency, formatCompactNumber } from "@/lib/formatters"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"

export function UsageCostsPage() {
  const { data: models } = useQuery({ queryKey: queryKeys.usage.models, queryFn: () => api.usage.getModelUsage() })
  const { data: workflows } = useQuery({ queryKey: ["usage", "workflows"], queryFn: () => api.usage.getWorkflowUsage() })
  const { data: projects } = useQuery({ queryKey: ["usage", "projects"], queryFn: () => api.usage.getProjectUsage() })

  return (
    <div className="space-y-8">
      <PageHeader 
        title="Cost Breakdown"
        description="Detailed attribution of costs across models, workflows, and projects."
      />

      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Model Usage</CardTitle>
            <CardDescription>Costs generated by foundational AI models</CardDescription>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Provider</TableHead>
                  <TableHead>Model</TableHead>
                  <TableHead className="text-right">Input Tokens</TableHead>
                  <TableHead className="text-right">Output Tokens</TableHead>
                  <TableHead className="text-right">Cost</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {models?.map((m) => (
                  <TableRow key={m.model}>
                    <TableCell className="font-medium">{m.provider}</TableCell>
                    <TableCell><Badge variant="secondary">{m.model}</Badge></TableCell>
                    <TableCell className="text-right">{formatCompactNumber(m.inputTokens)}</TableCell>
                    <TableCell className="text-right">{formatCompactNumber(m.outputTokens)}</TableCell>
                    <TableCell className="text-right">{formatCurrency(m.cost)}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        <div className="grid md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Workflows</CardTitle>
              <CardDescription>Top spending workflows</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Workflow</TableHead>
                    <TableHead className="text-right">Runs</TableHead>
                    <TableHead className="text-right">Total Cost</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {workflows?.map((wf) => (
                    <TableRow key={wf.id}>
                      <TableCell className="font-medium max-w-[200px] truncate" title={wf.name}>{wf.name}</TableCell>
                      <TableCell className="text-right">{formatCompactNumber(wf.runs)}</TableCell>
                      <TableCell className="text-right">{formatCurrency(wf.cost)}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Projects</CardTitle>
              <CardDescription>Top spending projects</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Project</TableHead>
                    <TableHead className="text-right">Builds</TableHead>
                    <TableHead className="text-right">Total Cost</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {projects?.map((proj) => (
                    <TableRow key={proj.id}>
                      <TableCell className="font-medium max-w-[200px] truncate" title={proj.name}>{proj.name}</TableCell>
                      <TableCell className="text-right">{formatCompactNumber(proj.buildRuns)}</TableCell>
                      <TableCell className="text-right">{formatCurrency(proj.cost)}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
