export const INTEGRATION_SECRETS_PROVIDER = Symbol(
  "INTEGRATION_SECRETS_PROVIDER",
);
export const INTEGRATION_OAUTH_HTTP_CLIENT = Symbol(
  "INTEGRATION_OAUTH_HTTP_CLIENT",
);
export const INTEGRATION_CONNECTOR_RUNTIME_CONFIG = Symbol(
  "INTEGRATION_CONNECTOR_RUNTIME_CONFIG",
);
