export const BILLING_PROVIDER = Symbol("BILLING_PROVIDER");
export const BILLING_SECRETS_PROVIDER = Symbol("BILLING_SECRETS_PROVIDER");
export const BILLING_WEBHOOK_SECRET_REF = Symbol(
  "BILLING_WEBHOOK_SECRET_REF",
);
