# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from alter.planner.v1 import planner_pb2 as alter_dot_planner_dot_v1_dot_planner__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in alter/planner/v1/planner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlannerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decompose = channel.unary_unary(
                '/alter.planner.v1.PlannerService/Decompose',
                request_serializer=alter_dot_planner_dot_v1_dot_planner__pb2.DecomposeRequest.SerializeToString,
                response_deserializer=alter_dot_planner_dot_v1_dot_planner__pb2.DecomposeResponse.FromString,
                _registered_method=True)
        self.Replan = channel.unary_unary(
                '/alter.planner.v1.PlannerService/Replan',
                request_serializer=alter_dot_planner_dot_v1_dot_planner__pb2.ReplanRequest.SerializeToString,
                response_deserializer=alter_dot_planner_dot_v1_dot_planner__pb2.ReplanResponse.FromString,
                _registered_method=True)
        self.SelectStrategy = channel.unary_unary(
                '/alter.planner.v1.PlannerService/SelectStrategy',
                request_serializer=alter_dot_planner_dot_v1_dot_planner__pb2.SelectStrategyRequest.SerializeToString,
                response_deserializer=alter_dot_planner_dot_v1_dot_planner__pb2.SelectStrategyResponse.FromString,
                _registered_method=True)


class PlannerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Decompose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlannerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decompose': grpc.unary_unary_rpc_method_handler(
                    servicer.Decompose,
                    request_deserializer=alter_dot_planner_dot_v1_dot_planner__pb2.DecomposeRequest.FromString,
                    response_serializer=alter_dot_planner_dot_v1_dot_planner__pb2.DecomposeResponse.SerializeToString,
            ),
            'Replan': grpc.unary_unary_rpc_method_handler(
                    servicer.Replan,
                    request_deserializer=alter_dot_planner_dot_v1_dot_planner__pb2.ReplanRequest.FromString,
                    response_serializer=alter_dot_planner_dot_v1_dot_planner__pb2.ReplanResponse.SerializeToString,
            ),
            'SelectStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectStrategy,
                    request_deserializer=alter_dot_planner_dot_v1_dot_planner__pb2.SelectStrategyRequest.FromString,
                    response_serializer=alter_dot_planner_dot_v1_dot_planner__pb2.SelectStrategyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alter.planner.v1.PlannerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alter.planner.v1.PlannerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlannerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Decompose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.planner.v1.PlannerService/Decompose',
            alter_dot_planner_dot_v1_dot_planner__pb2.DecomposeRequest.SerializeToString,
            alter_dot_planner_dot_v1_dot_planner__pb2.DecomposeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.planner.v1.PlannerService/Replan',
            alter_dot_planner_dot_v1_dot_planner__pb2.ReplanRequest.SerializeToString,
            alter_dot_planner_dot_v1_dot_planner__pb2.ReplanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.planner.v1.PlannerService/SelectStrategy',
            alter_dot_planner_dot_v1_dot_planner__pb2.SelectStrategyRequest.SerializeToString,
            alter_dot_planner_dot_v1_dot_planner__pb2.SelectStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
